# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.activity.linkedin.share_news_item:
        bundle_name: "campaignchain/activity-linkedin"
        module_identifier: "campaignchain-linkedin-share-news-item"
        location: %campaignchain.location.linkedin.user%
        equals_operation: true
        operations:
            - %campaignchain.operation.linkedin.share_news_item%
        handler: "campaignchain.activity.controller.handler.linkedin.share_news_item"

services:
    campaignchain.activity.controller.linkedin.share_news_item:
        class: CampaignChain\CoreBundle\Controller\Module\ActivityModuleController
        calls:
            - [setContainer, ["@service_container"]]
            - [setParameters, ["%campaignchain.activity.linkedin.share_news_item%"]]
    campaignchain.activity.controller.handler.linkedin.share_news_item:
        class: CampaignChain\Activity\LinkedInBundle\Controller\ShareNewsItemHandler
        arguments:
            - "@campaignchain.operation.linkedin.news_item"
            - "@campaignchain.channel.linkedin.rest.client"
            - "@campaignchain.job.operation.linkedin.share_news_item"
            - "@templating"